//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DikayaMagiya.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DikayaMagiya.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кастер оказывается сбитым автомобилем (1d100 единиц урона, спасбросок от оружия дыхания для половины урона).
        ///Кастер сходит с ума, если разумен; спасбросок от заклинаний и безумия длится 1d4 недели, в противном случае — навсегда, хотя его можно вылечить с помощью соответствующей магии.
        ///Молния поражает заклинателя с неба на уровне действия этой волны. Заклинатель не имеет права на спасбросок, но те, кто находится в радиусе пяти футов, должны спасбросок на половину урона.
        ///Случайное существо с внешних планов [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string randomEff {
            get {
                return ResourceManager.GetString("randomEff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1	Заклинатель мгновенно перемещается влево на 25 футов (или до ближайшего препятствия), на земле остается полыхающий огненный след от начального до конечной точки перемещения.
        ///2	Заклинание не срабатывает... пока не пройдет 1d4 раундов.
        ///3	Рыбный день. От заклинателя исходит сильный запах рыбы. Цель заклинания тоже пахнет рыбой. Если целью является область, то вся область пахнет рыбой. Ели заклинание принимает форму снаряда (магическая стрела и т.п.), то снаряд становится рыбой (тип урона сохраняется).
        ///4	В [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string randommagic {
            get {
                return ResourceManager.GetString("randommagic", resourceCulture);
            }
        }
    }
}
